// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94kWawaC6YXKmOBFEvLpH24BuGDbBrII',
    appId: '1:131375956513:android:aee19f77e279a0590d1960',
    messagingSenderId: '131375956513',
    projectId: 'novelflex-890a6',
    storageBucket: 'novelflex-890a6.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQXhO3pS9gxbdaLvto2OmZEeGDgd54FM',
    appId: '1:131375956513:ios:1c039286a015c2730d1960',
    messagingSenderId: '131375956513',
    projectId: 'novelflex-890a6',
    storageBucket: 'novelflex-890a6.appspot.com',
    androidClientId: '131375956513-j1l6q9ir7reh999anqbdvmuh4l9pd3ro.apps.googleusercontent.com',
    iosClientId: '131375956513-gcbl69vikj8tubf9g2klnbhasf8hpf6h.apps.googleusercontent.com',
    iosBundleId: 'com.appcom.estisharati.novel.flex.novelflex',
  );
}
